language: cpp

dist: xenial
sudo: required

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - WIRESHARK_BRANCH=master-2.6 PLUGIN_DIR=$TRAVIS_BUILD_DIR BUILD_STANDALONE=no
  - WIRESHARK_BRANCH=master-2.6 PLUGIN_DIR=$TRAVIS_BUILD_DIR BUILD_STANDALONE=yes

matrix:
  exclude:
    # Exclude gcc build on OSX
    - os: osx
      compiler: gcc
    # Exclude standalone build on OSX
    - os: osx
      env: WIRESHARK_BRANCH=master-2.6 PLUGIN_DIR=$TRAVIS_BUILD_DIR BUILD_STANDALONE=yes
  allow_failures:
    - os: osx

before_install:
  - echo $TRAVIS_OS_NAME

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        ${PLUGIN_DIR}/tools/osx-provision-source.sh;
        PATH=/usr/local/opt/qt5/bin:$PATH;
    fi

  # See https://github.com/travis-ci/travis-ci/issues/5326
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ ${BUILD_STANDALONE} == "no" ]; then
        ${PLUGIN_DIR}/tools/ubuntu-provision-source.sh;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ ${BUILD_STANDALONE} == "yes" ]; then
        ${PLUGIN_DIR}/tools/ubuntu-provision-standalone.sh;
    fi

install:
  - if [ ${BUILD_STANDALONE} == "no" ]; then
        ${PLUGIN_DIR}/tools/ubuntu-build-source.sh;
        export PATH=${PATH}:${HOME}/wireshark-${WIRESHARK_BRANCH}/build/run;
        export WIRESHARK_RUN_FROM_BUILD_DIRECTORY=1;
    fi
  - if [ ${BUILD_STANDALONE} == "yes" ]; then
        ${PLUGIN_DIR}/tools/ubuntu-build-standalone.sh;
    fi

script:
  - python ${PLUGIN_DIR}/tests/__init__.py

before_deploy:
  - if [ ${BUILD_STANDALONE} == "no" ]; then
        cp build/run/plugins/2.6/epan/sap.so build/sap-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-x86-64.so;
    fi
  - if [ ${BUILD_STANDALONE} == "yes" ]; then
        mv build/sap.so build/sap-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-x86-64.so;
    fi

deploy:
    provider: releases
    api_key:
        secure: "HmUIZ6L/W2Njxnm8z1xWrtka1cxzQRZo62asHljFXYj9QCMBmCDGr3CHvJW42D9c8dV3Q7f2HOO0WEatDo+1IWtoZZtuQ8Jbxhz5cegobhuO5Wj7q+45DPf31/dILufDG9Sy2vmgJV0EWxuvYJXMelxjd8+yfXCtGLrZbpcWUPU="
    file: "build/*.so"
    file_glob: true
    skip_cleanup: true
    on:
        tags: true
        repo: SecureAuthCorp/SAP-Dissection-plug-in-for-Wireshark
        condition: "${BUILD_STANDALONE} == \"yes\" || ${TRAVIS_OS_NAME} == \"osx\""
