dist: xenial
language: python
python:
- '3.6'
- '3.7'
- '3.8-dev'
install:
- pip install -r requirements.txt
script:
- pytest
notifications:
  email: false
  slack:
    rooms:
      secure: UwxZLjlYpWP8a/bzTD83LoAmA4zoAGp9CgdtLYsx742gSQLBqP0MVTac7yCuXZq0hWk3L1Hgbah03pi0kksUtxxD4Yq0Kj5zVdIWOxpaSTlJTpVmm05wlTZxk1AFWmb6MfvZpGio1X+nkwbNQCbHEqvc/SymnXzP7L0CtY0J/ow8zNxC3YHEB8FjI6ryrsShQWEEkR5iBcAKPIx3oaWr8eNd8e/4+68GuNI5AQurZU10uxUmsOlOUlk+ktO1kXEHAaTdZ3o5npgLVvLNZNBdrzABpTGsAQUZahtleWZFC204NnxAY7m0FSpvC+wqI8pL+i5Tg9EdYNyi6HGl9UUZZaTsGXNSePHFFFRGl5W97NglIUWRz+v7iZUH85nQtEYeaKiUmTP4Ohc4yzUXX9U3G6xLQMDSdP19ur7Xvv/0EAt4bKf6AZUBFDhTUA2Z7QIfsfdcuJYt6wtnSiUWrFYYoKs2EwTFb3Rt9plJMiZIrqTov6Fyj9I9XukqgUt/NHM4kPnQqdONGSm494CP++9CzI6OwlAi8P11s7/F5zqGn3ta/X1GOwUkNm+MBv33QAJPA4INPSTEsjqmqfnU6WdXk3ZL7E51u3XhbXmPduwzXqUnftwnbCR60IhP9nOnZkv4onU89SPzCMJaOfWHRgkQpTZn2Z7VE98dAVE02T3mjt0=
    on_success: always
    on_failure: always
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"